// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYcE6YFZ2DF4bSVIW7E8ki8CfZZDaYtSM',
    appId: '1:918660611303:web:e53da662df38f708ff3642',
    messagingSenderId: '918660611303',
    projectId: 'chating-418dd',
    authDomain: 'chating-418dd.firebaseapp.com',
    storageBucket: 'chating-418dd.appspot.com',
    measurementId: 'G-XKV1B1W18C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8Lyvfw0EQLVcVyR0yP70qH8UI8YZwCg',
    appId: '1:918660611303:android:33ae2fdc51208b34ff3642',
    messagingSenderId: '918660611303',
    projectId: 'chating-418dd',
    storageBucket: 'chating-418dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6wqutQlVHsR3cVPCyT5UNJuJECC-ty0',
    appId: '1:918660611303:ios:9069fc4bd633ade9ff3642',
    messagingSenderId: '918660611303',
    projectId: 'chating-418dd',
    storageBucket: 'chating-418dd.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh6wqutQlVHsR3cVPCyT5UNJuJECC-ty0',
    appId: '1:918660611303:ios:9069fc4bd633ade9ff3642',
    messagingSenderId: '918660611303',
    projectId: 'chating-418dd',
    storageBucket: 'chating-418dd.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYcE6YFZ2DF4bSVIW7E8ki8CfZZDaYtSM',
    appId: '1:918660611303:web:2d02fe56da9c17e2ff3642',
    messagingSenderId: '918660611303',
    projectId: 'chating-418dd',
    authDomain: 'chating-418dd.firebaseapp.com',
    storageBucket: 'chating-418dd.appspot.com',
    measurementId: 'G-K6QQ3X0CBP',
  );
}
